minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@dialine/astro-site'
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
engineStrict: true
strictDepBuilds: true
nodeLinker: isolated
allowBuilds:
  esbuild: true
  sharp: true
